# Generated by Django 5.1.4 on 2025-01-24 06:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtbranch',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='revenuereport',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='courtstaff',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='court',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='courtmanager',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courtstaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='revenuereport',
            name='generated_by',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='id',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='court',
            old_name='id',
            new_name='court_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='systemadmin',
            old_name='id',
            new_name='systemAdmin_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_hours',
        ),
        migrations.RemoveField(
            model_name='court',
            name='time_slots',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_permissions_set', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='BadmintonHall',
            fields=[
                ('badminton_hall_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badminton_halls', to='user.systemadmin')),
            ],
        ),
        migrations.AddField(
            model_name='court',
            name='badminton_hall',
            field=models.ForeignKey(default='h1', on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='user.badmintonhall'),
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('total_revenue', models.FloatField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenues', to='user.court')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('time_frame', models.CharField(max_length=100)),
                ('price_per_frame', models.DecimalField(decimal_places=2, max_digits=10)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='user.court')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot',
            field=models.ForeignKey(default='s1', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='user.slot'),
        ),
        migrations.DeleteModel(
            name='CheckIn',
        ),
        migrations.DeleteModel(
            name='CourtBranch',
        ),
        migrations.DeleteModel(
            name='CourtManager',
        ),
        migrations.DeleteModel(
            name='CourtStaff',
        ),
        migrations.DeleteModel(
            name='RevenueReport',
        ),
    ]
