# Generated by Django 5.1.4 on 2025-01-24 07:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0002_remove_courtbranch_manager_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotTemplate',
            fields=[
                ('template_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('time_frame', models.CharField(max_length=50)),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flexible_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='court',
            new_name='court_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='customer',
            new_name='customer_id',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='court',
            old_name='court_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='booking',
            new_name='booking_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='slot',
            old_name='court',
            new_name='court_id',
        ),
        migrations.RenameField(
            model_name='systemadmin',
            old_name='systemAdmin_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='badmintonhall',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='court',
            name='badminton_hall',
        ),
        migrations.RemoveField(
            model_name='court',
            name='hourly_rate_daily',
        ),
        migrations.RemoveField(
            model_name='court',
            name='hourly_rate_fixed',
        ),
        migrations.RemoveField(
            model_name='court',
            name='hourly_rate_flexible',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='price_per_frame',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='time_frame',
        ),
        migrations.AddField(
            model_name='badmintonhall',
            name='systemAdmin_id',
            field=models.ForeignKey(default='h1', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='user.systemadmin'),
        ),
        migrations.AddField(
            model_name='booking',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_hours',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='badminton_hall_id',
            field=models.ForeignKey(default='c1', on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='user.badmintonhall'),
        ),
        migrations.AddField(
            model_name='payment',
            name='customer_id',
            field=models.OneToOneField(default='p1', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='user.customer'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='CourtManager',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_manager', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='CourtStaff',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('badminton_hall_id', models.ForeignKey(default='cs1', on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='user.badmintonhall')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_staff', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('badminton_hall_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='user.badmintonhall')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='slot',
            name='template',
            field=models.ForeignKey(default='s1', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='user.timeslottemplate'),
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
