# Generated by Django 5.1.4 on 2025-01-27 08:00

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadmintonHall',
            fields=[
                ('badminton_hall_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('systemAdmin_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlotTemplate',
            fields=[
                ('template_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(max_length=20)),
                ('time_frame', models.CharField(max_length=50)),
                ('fixed_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flexible_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='available', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('badminton_hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='app1.badmintonhall')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('booking_type', models.CharField(choices=[('fixed', 'Fixed'), ('daily', 'Daily'), ('flexible', 'Flexible')], max_length=20)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default='00:00:00')),
                ('end_time', models.TimeField(default='00:00:00')),
                ('status', models.BooleanField(default=False)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app1.court')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app1.booking')),
                ('customer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='app1.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('court_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app1.court')),
                ('template_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app1.timeslottemplate')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='app1.slot'),
        ),
        migrations.AddField(
            model_name='badmintonhall',
            name='systemAdmin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='app1.systemadmin'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('guest', 'Guest'), ('customer', 'Customer'), ('court_manager', 'Court Manager'), ('court_staff', 'Court Staff'), ('admin', 'System Admin')], default='guest', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='systemadmin',
            name='Thongtintaikhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_admin', to='app1.user'),
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('revenueReport_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('badminton_hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='app1.badmintonhall')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='Thongtintaikhoan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='app1.user'),
        ),
        migrations.CreateModel(
            name='CourtStaff',
            fields=[
                ('courtStaff_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('badminton_hall_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='app1.badmintonhall')),
                ('Thongtintaikhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_staff', to='app1.user')),
            ],
        ),
        migrations.CreateModel(
            name='CourtManager',
            fields=[
                ('courtManager_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('Thongtintaikhoan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_manager', to='app1.user')),
            ],
        ),
    ]
