# Generated by Django 5.1.6 on 2025-02-13 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badmintonhall',
            name='court_manager',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badminton_hall', to='app1.courtmanager'),
        ),
    ]
