# Generated by Django 5.1.4 on 2025-02-11 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtstaff',
            name='court',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_staff', to='app1.court'),
        ),
    ]
