# Generated by Django 5.1.4 on 2025-02-16 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='courtstaff',
            name='court',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_staff', to='app1.court'),
        ),
        migrations.AlterField(
            model_name='courtstaff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_staff', to=settings.AUTH_USER_MODEL),
        ),
    ]
