# Generated by Django 5.1.4 on 2025-02-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_booking_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_id',
        ),
    ]
