# Generated by Django 5.1.4 on 2025-01-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('badminton_hall_id', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('operating_hours', models.CharField(max_length=255)),
                ('available_slots', models.JSONField()),
            ],
        ),
    ]
