# Generated by Django 5.1.4 on 2025-02-06 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_badmintonhall_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
