# Generated by Django 5.1.4 on 2025-01-27 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_court_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badmintonhall',
            name='systemAdmin_id',
        ),
    ]
