# Generated by Django 5.1.6 on 2025-02-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_courtmanager_payment_accounts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentaccount',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='court_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='app1.courtmanager'),
        ),
    ]
