# Generated by Django 5.1.6 on 2025-02-09 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_badmintonhall_badminton_hall_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badmintonhall',
            name='address',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='badmintonhall',
            name='badminton_hall_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='badmintonhall',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
