# Generated by Django 5.1.4 on 2025-01-16 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_court'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('total_revenue', models.FloatField()),
                ('month', models.FloatField()),
                ('quarter', models.FloatField()),
                ('year', models.FloatField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.court')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('slot_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('time_frame', models.CharField(max_length=100)),
                ('price_per_frame', models.FloatField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.court')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('schedule_type', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.court')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.slot')),
            ],
        ),
    ]
