# Generated by Django 5.1.4 on 2025-02-06 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_court_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='court_images/'),
        ),
        migrations.AlterField(
            model_name='court',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
