# Generated by Django 5.1.6 on 2025-02-14 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_paymentaccount_accountnumber_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_manager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='accountNumber',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentaccount',
            name='court_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='app1.courtmanager'),
        ),
    ]
