# Generated by Django 5.1.4 on 2025-02-04 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_courtmanager_thongtintaikhoan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountHolder', models.CharField(max_length=100)),
                ('accountNumber', models.CharField(max_length=50)),
                ('paymentMethod', models.CharField(choices=[('bank', 'Ngân hàng'), ('momo', 'Momo')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
            ],
        ),
        migrations.AddField(
            model_name='courtmanager',
            name='payment_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_manager', to='app1.paymentaccount'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='app1.paymentaccount'),
        ),
    ]
